### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by lucasoshiro** [lucasoshiro/oshit#1]
- [ ] status
- [ ] three way merge
- [ ] stash
- [ ] cherry-pick
- [ ] diff

**Comment by d3adb5** [comment]
Might be worth splitting this issue into multiple so one can better keep track of the tasks that have been completed already and what is necessary for for them. E.g.:

## #7 Add packfile compatibility

- [x] Non-deltified objects
- [ ] Deltified objects
- [ ] Read size from packfile
- [ ] Garbage collection

## #8 Implement merge command & strategies

- [x] 3-way merge
- [ ] diff3
